### ISSUE TITLE
Project File - set buffered transaction groups, not automatic transaction groups

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#104]
Solution: buffered transaction groups, not automatic transaction groups in the project settings

_Originally posted by @urskaufmann in https://github.com/teksi/wastewater/discussions/72#discussioncomment-8178086_

**Comment by sjib** [comment]
@ponceta Can you integrate this in the latest project file in coordination with @urskaufmann

**Comment by 3nids** [comment]
no, this should be automatic transaction

**Comment by sjib** [comment]
> no, this should be automatic transaction

@3nids So what is the conclusion from the discussion with Urs this morning?

**Comment by 3nids** [comment]
Fixed in #137
