### ISSUE TITLE
Datamodel - Cyclic relations on classes missing

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#107]
The attribute and relation log_card.fk_main_structure and fk_next_special_building are missing in the datamodel.

!!@ comment = "Assoziation"
ASSOCIATION Stammkarte_HauptbauwerkAssoc =
  HauptbauwerkRef  -- {0..1} Stammkarte;
  Stammkarte_HauptbauwerkAssocRef -- {0..*} Stammkarte;
END Stammkarte_HauptbauwerkAssoc;

!!@ comment = "Assoziation"
ASSOCIATION Stammkarte_Naechstes_SBWAssoc =
  Naechstes_SBWRef  -- {0..1} Stammkarte;
  Stammkarte_Naechstes_SBWAssocRef -- {0..*} Stammkarte;
END Stammkarte_Naechstes_SBWAssoc;

**Comment by sjib** [comment]
Same with measuring_point.fk_reference_station

 !!@ comment = "Assoziation"
ASSOCIATION Messstelle_ReferenzstelleAssoc =
  ReferenzstelleRef  -- {0..*} Messstelle;
  Messstelle_ReferenzstelleAssocRef -- {0..*} Messstelle;
END Messstelle_ReferenzstelleAssoc;

**Comment by sjib** [comment]
These are all relations on the class itself.
@ponceta @domi4484 Can they be treated like other relations or should there be an extra table xxx_hierachy?

Many years ago I implemented this on MS ACCESS like this. Is this still the way to go also with Postgres?

```
                'RE_MESSSTELLE_HIERARCHIE
                Print #1, "CREATE TABLE RE_MESSSTELLE_HIERARCHIE( OBJ_ID  Text(" & OBJ_IDLengthString & ") not null, FS_MESSSTELLE Text (" & OBJ_IDLengthString & "), FS_REFERENZSTELLE Text (" & OBJ_IDLengthString & "));"
                
                Print #1, "ALTER TABLE RE_MESSSTELLE_HIERARCHIE ADD CONSTRAINT medrel204 FOREIGN KEY (FS_MESSSTELLE) REFERENCES MESSSTELLE(OBJ_ID);"
                Print #1, "ALTER TABLE RE_MESSSTELLE_HIERARCHIE ADD CONSTRAINT medrel205 FOREIGN KEY (FS_REFERENZSTELLE) REFERENCES MESSSTELLE(OBJ_ID);"
 ```

**Comment by sjib** [comment]
Or is it enough to set DEREFERABLE?

see https://github.com/teksi/wastewater/issues/98#issuecomment-1911723648

**Comment by ponceta** [comment]
Not clear to me : 
- [ ] Missing from initial datamodel implementation -> @sjib 
- [ ] Missing from adaptation to tww -> @3nids 
- [ ] Out of project scope and new -> bugfixing ?

**Comment by sjib** [comment]
@ponceta It is "Missing from initial datamodel implementation" - pull request https://github.com/teksi/wastewater/pull/158 added to solve this issue
