### ISSUE TITLE
Old views cleanup

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#11]
> @ponceta - a comment from Urs: Unter wastewater/datamodel/app/view/additional_views hat es ganz viele alte Views, zu denen es in der Version 2020 gar keine Klasse mehr gibt (z.B. das ganze Gewässer). Diese unbrauchbaren Views sollte man doch alle löschen (nicht alle additional, nur die unbrauchbaren)…
> 
> Freundliche Grüsse Urs Kaufmann
> 
> https://github.com/teksi/wastewater/tree/2023-11-21-datamodel_corrections/datamodel/app/view/additional_views
> 
> Should we sort these out now or in a new pull request?

Yes, this would be more than welcome, it's difficult on the development side to distinguish what is active from what is history.

**Comment by 3nids** [comment]
Let's put all unused views in an old folder for the moment?

**Comment by urskaufmann** [comment]
This old 2015-version views are vw-
Blocking_debris
Chute
Cooperative
Dam
Ford
Ground_water_protection_perimeter
Ground_water_protection_zone
Lake
Lock
Passage
River
Rock_ramp
