### ISSUE TITLE
Interlis Import and other Errors

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#112]
Create new database with  (links in #72 )
tww_dev_structure_with_value_lists.sql (file has date 16.01.2024, download 27.1.2024)
Plugin download 27.1.2024
Project download 27.1.12024
QGIS 3.28.15

When starting project, I get this:   INFO    Aufgabe gescheitert : Lade 2infra/infraprogs/QGIS 3.0/bin: This path is still in the project.
Then I get message about missing layers (network layers) -> refresh materialized views did not run with this sql

Then I started Import Interlis with the test-dataset-organisations.xtf (Musterdatensatz).
-> Error: disable symbology_trigger not in the database...

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function tww_sys.disable_symbology_triggers() does not exist LINE 1: SELECT tww_sys.disable_symbology_triggers();               ^ HINT:  No function matches the given name and argument types. You might need to add explicit type casts. [SQL: SELECT tww_sys.disable_symbology_triggers();] (Background on this error at: http://sqlalche.me/e/13/f405)

**Comment by cymed** [comment]
tww_sys.disable_symbology_triggers was introduced with https://github.com/teksi/wastewater/pull/88. When did you set up your DB?

**Comment by urskaufmann** [comment]
As I wrote: I have downloaded datamodel-dumps.zip on Saturday 27.1. from the link in #72 . The files in zip have modified date 16.1.2024,  means they are not uptodate.

**Comment by cymed** [comment]
Tagging @3nids for updating the datamodel dumps in #72

**Comment by tomep** [comment]
I have the same error by import the test-dataset-organisations.xtf and the test-dataset-DSS.xtf:
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function tww_sys.disable_symbology_triggers() does not exist LINE 1: SELECT tww_sys.disable_symbology_triggers();               ^ HINT:  No function matches the given name and argument types. You might need to add explicit type casts. [SQL: SELECT tww_sys.disable_symbology_triggers();] (Background on this error at: http://sqlalche.me/e/13/f405)

**Comment by 3nids** [comment]
dump updated in doc
