### ISSUE TITLE
tww tool change reach direction does not work

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#123]
I downloaded and installed plugin this evening (31.1.2024)

tool "change reach direction" does not work. And there are two different behaviour:
when transactionmode = buffered transactiongroups then  I get this error in the protokoll:
![image](https://github.com/teksi/wastewater/assets/1257403/cef0ed3d-b75a-4b64-8e3c-0020521b57a6)

when transactionmode = automatic transactiongroups then I get no error, just warnings and nothing happens, reach directions do not change:
![image](https://github.com/teksi/wastewater/assets/1257403/6e7f6261-dd57-4e5a-b4c5-5c7dfaa5e097)

**Comment by ponceta** [comment]
@3nids it looks like something is missing plugin/datamodel side

**Comment by 3nids** [comment]
I'm not getting any error here

**Comment by ponceta** [comment]
@ponceta checks with @3nids

**Comment by ponceta** [comment]
@3nids Everything is coded as before, I expect a change of behaviour on QGIS side, could you or @domi4484 take a look at it?

**Comment by ponceta** [comment]
Nevermind, didn't see the upcoming fix.
