### ISSUE TITLE
missing entries in tww_sys.dictionnary_od_tables for _aquifier & _planning_zone

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#134]
> we have tables in the od schema which are not listed in tww_sys.dictionnary_od_table:
 _planning_zone => ? _aquifier => ?

@3nids Here I have to create two additional tww_dictionary_ files that corresponds to
- 51_aquifier_2015.sql
- 52_planning_zone_2015.sql

_Originally posted by @sjib in https://github.com/teksi/wastewater/issues/119#issuecomment-1922222932_

**Comment by cymed** [comment]
General question: would it be smarter to populate tww_sys.dictionary_od_values/field/table with event triggers? [Link to postgres docs](https://www.postgresql.org/docs/current/event-triggers.html)
