### ISSUE TITLE
Default dataowner / dataprovider

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#135]
Issue :
**dataowner** / **dataprovider** should not be NULL

TODO :
 - [x] Rethink and propose a way to handle default dataowner / dataprovider
 - [x] Propose a database simplification https://github.com/teksi/wastewater/pull/173
 - [ ] Add to .qgs project https://github.com/teksi/wastewater/issues/237
 - [ ] Add to documentation 

Goal :
dataowner / dataprovider are correctly field in a simple way for the end user

**Comment by sjib** [comment]
Prework from @urskaufmann 

Ich habe ein sql gebaut, welches die dataowner und provider einsetzt. Und zwar nicht alle mit default-Wert, sondern dort wo es nach mir Sinn macht, der entsprechende Wert des verknüpften Objektes einsetzt anstatt NULL. Also zB. die Haltungspunkt bekommen den gleichen Datenherr Provider wie die Haltungen.
In der Beilage das File dazu. Man kann es nicht auf einmal laufen lassen. Es muss zuerst der erste Teil laufen (default-Wert) dann im zweiten Teil die parent / related classes (dort muss man wohl auch noch aufpassen, wo über mehrere Stufen geerbt wird.
Jetzt muss man nur noch bei ch080qwzGE000001 und ch080qwzGE000002 die richtigen Defaultwerte einsetzen, dann sollte das funktionieren. Hat vermutlich auch noch Fehler, Testen ist etwas mühsam…
[update dataowner and provider.zip](https://github.com/teksi/wastewater/files/14139070/update.dataowner.and.provider.zip)

**Comment by cymed** [comment]
closed with #173
