### ISSUE TITLE
Add glossary files to transifex

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#140]
Glossary 

A glossary is a set of key terms, their part of speech, definitions, and translation. Glossaries help ensure consistency in translations. And they can be helpful when working with industry or brand-specific terms. Your Language Service Provider can often help you create a glossary before translations begin.

https://help.transifex.com/en/articles/6656069-terms-in-transifex#h_8c9c3820aa

Idea: Use the existing translation from od_dictionaries (class, attributes, values) and provide them to transifex to simplify documentation and always use the right model term translations.

@3nids Check out if these are the specifications for such a glossary file:
See https://help.transifex.com/en/articles/6225045-uploading-a-tmx-file

**Comment by 3nids** [comment]
from the doc:
> Uploading TMX files is a feature only available on the Premium plan and up.

So probably a won't fix for now

**Comment by ponceta** [comment]
Glossaries are now available to open source projects

**Comment by 3nids** [comment]
oops apparently not: https://www.transifex.com/pricing/

**Comment by sjib** [comment]
Transifex wants 500 CHF or more / per month if we need glossaries with a lot of features we do not need. Transifex looks like a tool for professional translators with thousands of translations per month.

Alternatives e.g. https://alternativeto.net/software/weblate/about/
It seems to support glossay: https://docs.weblate.org/en/latest/user/glossary.html

Any experience or other suggestions?

**Comment by ponceta** [comment]
We used to use glossaries for QGEP and I was able to create a glossary for TEKSI, it should maybe clarified what limitations are set for open source projects in terms of features and how we create such files.

**Comment by ponceta** [comment]
A glossary has been added today to Transifex with classes, attributes and values.
