### ISSUE TITLE
Handling of tww_app

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#147]
In the future, tww_app ought to be dropped and re-created on model updates (see #128). This requires some adaptations:

- [x] in create views, add a psycopg2 statement to drop tww_app
- [ ] Add a point in the developer's guide to **never** store any tables with ordinary data in txx_app (see #85 for a bad examples)
- [x] When dropping and re-creating tww_app, the default grants for tww_app need to be set differently

Furthermore, the current code of `create_views.py` only works inside the dockerised environment, as the relations to the plain sql views such as `/app/view/vw_dictionary_value_list.sql` are absolute. This poses problems for people using datamodel extensions who would like to re-create the views dynamically from their environments.

@ponceta Opinions?

**Comment by ponceta** [comment]
This is directly on the roadmap to release management and production for TEKSI wastewater.
