### ISSUE TITLE
vw_tww_import_xxx and vw_tww_export_xxx depend on vw_tww_wastewater_structure

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#148]
We don't want views depending on views in general. Imho we should alter these views.
Does someone know what the point of those export views is?

**Comment by ponceta** [comment]
This is wrong and should be fixed quickly. I look at it this afternoon!

**Comment by cymed** [comment]
See https://github.com/teksi/wastewater/pull/42/files#diff-1922c956ca8cf304f776b3d67427ed9ed30d36f146daa4876a7612ce490cf55a for vw_tww_import
