### ISSUE TITLE
Interlis-export: Handling of local extensions of harmonised organisation list

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#152]
When exporting an VSA DSS 2020.1 Interlis from a database, a functionality is needed to map local extensions to the organisation value list (see https://vsa.ch/wiki/organisation/) The VSA supports two options:

- map local extensions to 'ch20p3q400000094'
- export a separate xtf with the local extensions

Either way, we need a way to identify local extensions to the harmonised model. Imho the first option is easier to implement.

**Comment by cymed** [comment]
first step is made with #150 

To do:

- [ ] alter organisation export to only include local extensions

**Comment by sjib** [comment]
> * alter organisation export to only include local extensions

@cymed I would rather write:  Add export option for local extension organisations

The organisations are not included in the regular export with VSA-DSS 2020, as there is the VSA organisation dataset that covers (most) organisations.

**Comment by cymed** [comment]
Solved with #150
