### ISSUE TITLE
INTERLIS Import mechanical_pretreatment.fk_wastewater_structure not present

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#162]
When importing the test-dataset-DSS.xtf the following error appears:

```
Details: (psycopg2.errors.ForeignKeyViolation) insert or update on table "mechanical_pretreatment" violates foreign key constraint "rel_mechanical_pretreatment_wastewater_structure"
DETAIL: Key (fk_wastewater_structure)=(ch080qwzVA001062) is not present in table "wastewater_structure".
```

Feedback originally from @urskaufmann

**Comment by sjib** [comment]
@domi4484 Would a DEFERABLE help here?

https://github.com/teksi/wastewater/blob/2d122f75339aa65228f9fde3e7309463e883d3bb/datamodel/changelogs/0001/03_tww_db_dss.sql#L3933

**Comment by ponceta** [comment]
It would be a good thing to include for relation reference between object tables.

Not for value lists.

Document this decision and this new functionnality.

Define what best differable setting (deferrable / deferrable initially deferred)

TO be disscussed with @3nids and @domi4484

**Comment by domi4484** [comment]
> @domi4484 Would a DEFERABLE help here?
> 
> https://github.com/teksi/wastewater/blob/2d122f75339aa65228f9fde3e7309463e883d3bb/datamodel/changelogs/0001/03_tww_db_dss.sql#L3933

@sjib Yes it should probably help

**Comment by sjib** [comment]
Should be solved with https://github.com/teksi/wastewater/pull/178
