### ISSUE TITLE
vw_tww_overflow has no default obj_id

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#182]
The qgis project no longer include vw_leapingweir, vw_prank_weir and vw_pump, but only vw_tww_overflow. vw_tww_overflow does not have a default obj_id and if it had one, it couldn't distinguish the shortcuts. We have 2 options to continue:

1. Use vw_tww_overflow for creation, use shortcut of overflow
2. add the tree views and keep distinguishing the types in the shortcut

**Comment by sjib** [comment]
@urskaufmann Can you check on this?

**Comment by cymed** [comment]
So when creating a new object, you have a default value set for obj_id?

**Comment by urskaufmann** [comment]
There is a sequence seq_overflow_oid, the obj_id is prefix+OV+seq_overflow_oid. That works. The identifier stays NULL if nothing entered. That's not "teksi-like" (if identifier is not entered, then identifier is set to obj_id by default). On the other side, I think, the user should always set an identifer for overflows, that derives from the wastewater_structure identifier...

**Comment by cymed** [comment]
has been solved
