### ISSUE TITLE
Action digitize does not work

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#195]
When trying to digitize the detail of a wastewater structure with the action on the right click, it does not work

2024-04-09T09:20:01     WARNING    Ajouter une partie : La géométrie de la nouvelle partie est vide ou invalide.

![image](https://github.com/teksi/wastewater/assets/8614223/094d15e2-7728-4e11-8ddd-3109d3c03ab4)

**Comment by sjib** [comment]
Problem with QGIS - see https://github.com/teksi/wastewater/pull/196#issuecomment-2090108894

**Comment by ponceta** [comment]
Fixed by @3nids in QGIS Master, waiting for backport.

@3nids Could you send us the link of the backport to follow?

**Comment by 3nids** [comment]
It's not that simple as I thought. It seems we have 3 different behaviors (3.34, 3.36 and master).
Here is one of the PRs: https://github.com/qgis/QGIS/pull/57318
It needs further investigation.

**Comment by ponceta** [comment]
@3nids thank you for the feedback!

**Comment by sjib** [comment]
@urskaufmann @ponceta please add idea for workaround with Digitize drainage channel

**Comment by urskaufmann** [comment]
Workaround: Digitize first a drainage channel. You get a rectangle in the layer wastewater_structure. Change this rectangle with the Stützpunktwerkzeug (move vertex, add new vertex etc).

**Comment by ponceta** [comment]
As @urskaufmann said ;) In a more visual way :
![Digitize_workaround](https://github.com/teksi/wastewater/assets/8614223/0e72bd68-3cfc-4150-832f-454e271fcb05)

**Comment by ponceta** [comment]
Fixed in :

- [ ] QGIS 3.34.8
- [ ] QGIS 3.38.0

Available on june 21st.

I keep it open until this release is published.

![image](https://github.com/teksi/wastewater/assets/8614223/c0435be0-9bbe-4ee2-8062-bd7fb17c1538)

**Comment by ponceta** [comment]
This is now a requirement for TEKSI Wastewater (and QGEP I you want to use it on latest versions of QGIS)

**Comment by ponceta** [comment]
3.34.8 is already available through osgeo4w, it will soon be available from QGIS website too.

**Comment by ponceta** [comment]
3.34.8 is fixed and specified in requirements.
