### ISSUE TITLE
Is QGIS ready for 3d curved lines?

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#21]
The database uses 3d curved lines for reaches which is handled as a simple 3d linestring conversion through the views and application mechanisms.

It could be a good moment to check if we can't use it as a 3d curveline since QGIS has well evolved since 2016.

**Comment by cymed** [comment]
QGIS has supported CompoundCurveZ for quite a while, but PostGIS' ST_SetPoint requires LineString: https://postgis.net/docs/ST_SetPoint.html

**Comment by 3nids** [comment]
Also, any geometric operation on a curve (split line for instance) would result in a linestring (Geos, the geometry engine used in QGIS, currently lacks support for curves)
