### ISSUE TITLE
Layer issue project

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#226]
service='pg_tww' key='code' checkPrimaryKeyUnicity='0' table="tww_vl"."bio_ecol_assessment_type_water_body"

![image](https://github.com/teksi/wastewater/assets/8614223/7d94156d-2c42-4777-91e8-4c514de18dfb)

**Comment by urskaufmann** [comment]
I have no missing layer when starting the project I changed yesterday.
And I have then this layer in the project (copied from layerproperties) service='pg_tww' key='code' checkPrimaryKeyUnicity='0' table="tww_vl"."bio_ecol_assessment_type_water_body"

**Comment by urskaufmann** [comment]
When starting the project, there is still this hint: 
INFO    Aufgabe gescheitert : Lade 2infra/infraprogs/QGIS 3.0/bin

There are still 4 lines with  *2infra/infraprogs/QGIS 3.0/bin*
 in the qgs-file (it's an old path I do not use anymore since years)
