### ISSUE TITLE
TEKSI Documentation not working

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#228]
When I click on one of the languages to read the TEKSI docs, I get an error page

![20240430_teksi_documentation_error](https://github.com/teksi/wastewater/assets/1265865/6eb25b57-26b7-408f-a211-83ae37300be8)

![20240430_teksi_documentation_error2](https://github.com/teksi/wastewater/assets/1265865/e7d162f7-99dd-4979-993b-846286279ba9)

**Comment by ponceta** [comment]
I fixed the links but translations are broken. I opened another issue.

https://github.com/teksi/wastewater/issues/234
