### ISSUE TITLE
Not able to change wastewater_node_fields in main_node -tab

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#241]
vw_tww_wastewater_structure. I change identifier on general-tab (wastewater_structure.identifier) and change the two identifiers on maincover/mainnode-tab manually.
This works for cover.identifier (means structure_part.identifier), but it works not for wastewater_node.identifier(means wastewater_network_element.identifier). After reopening the window, there are two identifiers changes, no change for the node identifier.
If I want to change the node identifier, I have to go to wastewater_nodes-tab, where I can change.

Is the same for wastewater_node.remark. Is not the same for other wastewater_node fields like bottom_level. Some fields can be changed on the mainnode-tab (seems to be the fields with unique name), some fields can only be changed on the wastewater-nodes - tab (seems to be fields with names like identifer or remark, that exist also in other tables of this view).

By the way: same behaviour also in QGEP...

Something is not as it should be.
Is a bug also, if we create this new function of renaming all identifiers when renaming the wastewater_structure.identifier...

**Comment by ponceta** [comment]
Should be covered when #36 is integrated
