### ISSUE TITLE
Missing auditing functionality 01_audit.sql

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#246]
@ponceta 
Why is 01_audit.sql that we had in qgep missing in TEKSI wastewater?
https://github.com/QGEP/datamodel/blob/master/01_audit.sql

We loose all functionality for auditing in TEKSI Wastewater.

**Comment by ponceta** [comment]
Roadmap on TMMT handling logging aspects will be defined in https://github.com/teksi/TMMT/issues/12.
