### ISSUE TITLE
Adapt filter queries for INTERLIS export selection

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#257]
Update `if self.filtered:` queries with new knowledge from qgep enhancement here:
https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py

qgep enhancements see: https://github.com/QGEP/qgepqwat2ili/pull/144/files

**Comment by sjib** [comment]
should be mostly solved with https://github.com/teksi/wastewater/pull/266

**Comment by ponceta** [comment]
#266 has been merged, feel free to reopen if not solved enough
