### ISSUE TITLE
converting value list fk back to bigint

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#26]
With #4, the tww_vl.value_list_base's code is defined as integer, but all foreign keys are set as smallint. For vl extensions, this poses a problem because their range mustn't interfere with the code values of tww_vl.value_list_base and attribute_id of tww_sys.dictionary_od_field. convertign back to bigint leaves more room for that.

**Comment by 3nids** [comment]
ping @sjib

**Comment by sjib** [comment]
@cymed Can you point to the specific code lines that I should adapt?
