### ISSUE TITLE
Function Update* (labels) not running after INTERLIS import  

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#260]
- Created new database
- Run tww_dev_structure_with_value_list.sql 2024-06-19
- Started tww-project 2024-06-19 
- Imported vsa-demo-organisation and vsa-demo-data
- all _label* fields in vw_tww_wastewater_structure are empty -> no labels for manholes if scale is < 1:800

After xtf-import, these update functions should run automatic (or the user can choose, if they should run or not)

**Comment by sjib** [comment]
I think we just re-enabled the triggers, but did not run any functions:

https://github.com/teksi/wastewater/issues/144#issuecomment-1929166170

**Comment by sjib** [comment]
I was trying to `EXECUTE tww_app.update_wastewater_node_symbology(_all);`

and get the error
`ERROR:  Syntaxfehler bei ».«
LINE 1: EXECUTE tww_app.update_wastewater_node_symbology(_all);
                                         ^ 

FEHLER:  Syntaxfehler bei ».«
SQL state: 42601
Character: 16`

And with select tww_app.update_wastewater_node_symbology(_all);

```
ERROR:  Spalte »_all« existiert nicht
LINE 1: select tww_app.update_wastewater_node_symbology(_all);
                                                                                                   ^ 

FEHLER:  Spalte »_all« existiert nicht
SQL state: 42703
Character: 49

and with Call
`call tww_app.update_wastewater_node_symbology(_all);`
```

ERROR:  Spalte »_all« existiert nicht
LINE 1: call tww_app.update_wastewater_node_symbology(_all);
                                                      ^ 

FEHLER:  Spalte »_all« existiert nicht
SQL state: 42703
Character: 47

@cymed @ponceta What is the right why to run the functions?
```
```

**Comment by cymed** [comment]
_all is a bool variable. The function can be called tww_app.update_wastewater_node_symbology(NULL, True) to update all or tww_app.update_wastewater_node_symbology(obj_id) to update a specific entry.

**Comment by sjib** [comment]
![20240619_testdata_labels_1_3800](https://github.com/teksi/wastewater/assets/1265865/4b3451f1-bfa8-4d04-abf8-3cf36bc951c5)
![20240619_success_testdata](https://github.com/teksi/wastewater/assets/1265865/ade2a152-1eae-4674-b47e-4cc152d8cc0a)

If I re-run these queries I think it looks better

```
SELECT tww_app.wastewater_structure_update_fk_main_cover('', True);
SELECT tww_app.wastewater_structure_update_fk_main_wastewater_node('', True);
```

![20240619_testdata_2_update_mainnode_nochange](https://github.com/teksi/wastewater/assets/1265865/935b352a-59f9-404a-b731-337c1f1ccafd)
![20240619_testdata_1_update_maincover](https://github.com/teksi/wastewater/assets/1265865/597a691e-dbfe-4f2b-bd08-598b92a9aa50)

And then run also:
```
SELECT tww_app.update_wastewater_node_symbology(NULL, True);
SELECT tww_app.update_wastewater_structure_label(NULL, True);
SELECT tww_app.update_wn_symbology_by_overflow(NULL, True); 
```

**Comment by sjib** [comment]
@urskaufmann Did you included the view that displays overflows?
![20240619_testdata_overflows_not_displayed](https://github.com/teksi/wastewater/assets/1265865/60c092fc-6fcf-41cf-942a-2df9379c3327)

Or how would I get those lines?
Or is this still something that needs to be integrated @cymed ?

**Comment by cymed** [comment]
It's vw_tww_overflow in hydraulics

**Comment by sjib** [comment]
> It's vw_tww_overflow in hydraulics

Yes, the view is here (I found the pull for this https://github.com/QGEP/datamodel/pull/187) and the email communication. But I do not find the layer stile for it

**Comment by urskaufmann** [comment]
Yes, the lines are included in the project.
If you don't have lines, it can be because
- you have translated the name of the vw_wastewater_node (in a german project) to vw_Abwasserknoten. Then the Geometriegenerator in the symbol can not find the vw and you have to change the formula.
- a polygon of layer wastewater_structure is on top of your overflow-line -> change the Layerreihenfolge / enable Bestimmt Zeichenreihenfolge:
![image](https://github.com/teksi/wastewater/assets/1257403/9a7cc1a2-006e-45e7-8e43-f2c258488fab)

- there is no fk_overflow_to for the record.

**Comment by urskaufmann** [comment]
These 2 lines did run obviously with the import 
SELECT tww_app.wastewater_structure_update_fk_main_cover('', True);
SELECT tww_app.wastewater_structure_update_fk_main_wastewater_node('', True);

These 3 lines did not run, but must run with the import:
SELECT tww_app.update_wastewater_node_symbology(NULL, True);
SELECT tww_app.update_wastewater_structure_label(NULL, True);
SELECT tww_app.update_wn_symbology_by_overflow(NULL, True); 

And additionally: the user should be able to manualy run this lines whenever he wants. -> a new button or command in the ui to start this functions.

**Comment by sjib** [comment]
@urskaufmann Changing layer orders works for overflows - thanks for adapting in the project

![20240620_overflow_visible_changed_layer_order](https://github.com/teksi/wastewater/assets/1265865/b07b7390-8df4-432b-8ffa-36cb37ba2037)

**Comment by sjib** [comment]
solved with https://github.com/teksi/wastewater/pull/263
For not solved disussed point new issues were opened.
