### ISSUE TITLE
No module named 'sqlalchemy','geoalchemy2'

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#270]
When trying to use INTERLIS import button :

Error: Could not load Interlis importer due to unmet dependencies. See logs for more details.

- [ ] teksi_wastewater:No module named 'sqlalchemy'
- [ ] teksi_wastewater:No module named 'geoalchemy2'

**Comment by cymed** [comment]
You need to have sqlalchemy installed in your qgis installation path. if you installed qgis via osgeo4w, select the module in the installation gui

**Comment by sjib** [comment]
in gep the datamodel checked for that and installed it if not already there. So something to get again with the TMMT plugin

**Comment by ponceta** [comment]
Closing this for now.
