### ISSUE TITLE
Request Error : Instance is not present in the session

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#273]
This is just a small bug but if you unselect features when importing INTERLIS data and you click on the text of an unselected feature, this will display an error message because the feature is no longer in the cache session. 

This requires a lot of work on the interlis import tool and will not be fixed yet as you can ignore the error and continue your import as nothing happened.

![image](https://github.com/teksi/wastewater/assets/8614223/f756b21d-1801-4a0d-bb6b-eb7003060814)

![image](https://github.com/teksi/wastewater/assets/8614223/39f42636-b598-449e-b69a-62361336cd48)

**Comment by sjib** [comment]
@ponceta Still an issues with [Prelease 2024.0.2](https://github.com/teksi/wastewater/releases/tag/2024.0.2)

**Comment by ponceta** [comment]
> @ponceta Still an issues with [Prelease 2024.0.2](https://github.com/teksi/wastewater/releases/tag/2024.0.2)

Yes but fixed in master.

**Comment by ponceta** [comment]
Fix confirmed in 2024.0.3
