### ISSUE TITLE
Missing documentation on how to delete wastewater structure without deleting the corresponding network element

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#279]
There are practical examples where one needs to delete a wastewater structure but not the corresponding nodes . In the following picture, a reduction from 250 mm to 200 mm was modelled as a "manhole.other" 
![grafik](https://github.com/teksi/wastewater/assets/102035587/08ffe40c-decc-44e2-8cbe-9a178b6fab31) 

In QGEP, we could delete the entry in od_wastewater_structure and the corresponding wastewater nodes were kept. in TWW, the deletion of the structure cascades to the network element via wastewater_networkelement.fk_wastewater_node.  In order to keep the node, we must first unlink the node and then delete the structure. 
![grafik](https://github.com/teksi/wastewater/assets/102035587/db8913d4-3b11-4ac2-a2ba-84bda36d477e)
Note: the fk_main_wastewater_node does not need to be deleted.
This behaviour is not yet documented.

**Comment by ponceta** [comment]
A full rigourous approach would require to create a new node, connect reaches to it and then remove the full wastewater structure.

But I agree with you, this is a nice trick to avoid such manipulations which would be great to document.

Note : _Similar could be the opposite, document how to add a node to a wastewater structure where only the cover or the detailed polygon has been drawn._

**Comment by cymed** [comment]
> A full rigourous approach would require to create a new node, connect reaches to it and then remove the full wastewater structure.
> 
> But I agree with you, this is a nice trick to avoid such manipulations which would be great to document.
> 
> Note : _Similar could be the opposite, document how to add a node to a wastewater structure where only the cover or the detailed polygon has been drawn._

Drop an re-create is not an option if you have fk on the wastewater nodes from outside the cadastral part (i.e. catchment areas etc.)

**Comment by sjib** [comment]
Solved with https://github.com/teksi/wastewater/pull/291
