### ISSUE TITLE
VSA Test Data import fails

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#287]
**Describe the bug**
Due to mismatch between VSA organisations and organisations, INTERLIS import of the testdata fails.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Import VSA organisations
    https://vsa.ch/models/organisation/vsa_organisationen_2020_1.xtf
2. Import VSA test data
https://raw.githubusercontent.com/teksi/wastewater/main/plugin/teksi_wastewater/tests/data/test-dataset-DSS.xtf
3. See error

**Expected behavior**
VSA Testdata can be imported with standard procedure

**Screenshots / data**
![image](https://github.com/teksi/wastewater/assets/8614223/d30872ce-b458-45a6-bcb9-4abfe0eee99d)

![image](https://github.com/teksi/wastewater/assets/8614223/d153ce09-05a9-44a7-9240-7cf9f55eaefa)

![image](https://github.com/teksi/wastewater/assets/8614223/ef4990a2-d8a7-470b-b787-79cb730a3f16)

**Desktop (please complete the following information):**
 - TWW version 2024.0.RC2
 - QGIS Version 3.34.8
 - OS Win 10 x64

**Additional context**
This should be tested in CI.

**Comment by sjib** [comment]
@ponceta You missed to import the first part of organisations: 
https://raw.githubusercontent.com/teksi/wastewater/main/plugin/teksi_wastewater/tests/data/test-dataset-organisations.xtf

The VSA Testdata set has a few additional organisations that are not in the official VSA organisations - that is something that still comes from version 2015 of that dataset.
see https://github.com/teksi/wastewater/discussions/72

Just import that organisation dataset and then the import of your network data should work well.

**Comment by ponceta** [comment]
Solved.
