### ISSUE TITLE
INTERLIS importer can leave triggers disabled in case of error

### ISSUE THREAD

**Issue by domi4484** [teksi/wastewater#289]
The INTERLIS importer disable the symbology trigger for performance reasons and re.-enables them in the end.
If an error occurs in the middle, there is no error handling to re-enable the triggers and they will stay disabled until a successful import is run or manually enabled.

 - [ ] Proper error handling should be implemented in `interlis_importer_exporter.py` to ensure this can't happen.

- [ ] Additionally a check should be added when opening the project. If the triggers are disabled the user will see a warning dialog

- [ ] Add a button to manually recalculate the whole symbology functions on the database https://github.com/teksi/wastewater/issues/264

Edit @ponceta 16.07.2024

**Comment by ponceta** [comment]
I encounter this issue with every test import I actually do now.

![image](https://github.com/user-attachments/assets/5030903c-b3c0-4768-b2b2-9867a98368a6)

I should not have to run manually the symbology triggers after the import.

**Comment by domi4484** [comment]
@ponceta even on successful import the triggers are not re-enabled for you?

**Comment by domi4484** [comment]
@ponceta since #263 these additional querys are run at the end of import. Are there still other functions that needs to be executed in the end? Or is maybe just a QGIS canvas refresh missing?

```sql
        SELECT tww_app.update_wastewater_node_symbology(NULL, True);
        SELECT tww_app.update_wastewater_structure_label(NULL, True);
        SELECT tww_app.update_wn_symbology_by_overflow(NULL, True);
```

**Comment by ponceta** [comment]
> @ponceta since #263 these additional querys are run at the end of import. Are there still other functions that needs to be executed in the end? Or is maybe just a QGIS canvas refresh missing?
> 
> ```sql
>         SELECT tww_app.update_wastewater_node_symbology(NULL, True);
>         SELECT tww_app.update_wastewater_structure_label(NULL, True);
>         SELECT tww_app.update_wn_symbology_by_overflow(NULL, True);
> ```

I tried with latest plugin and datamodel and it now works as intended.
