### ISSUE TITLE
Add wastewater structure impossible

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#30]
```
2023-12-01T15:06:24     WARNING    Requête erronée : SAVEPOINT "qgise515e37aefa1424d8023" a retourné 7 [ERREUR: SAVEPOINT peut seulement être utilisé dans des blocs de transaction
             ]
```

Am I the only one having this error when creating wastewater structure?

**Comment by 3nids** [comment]
for reference https://github.com/qgis/QGIS/issues/25432
could it be that you added layers that don't share the exact same source definition and that they don't land in the same transaction group? (easy way to check: are all layers editable or only some of them?)

**Comment by urskaufmann** [comment]
That was the right hint. Seems it is the QGIS-problem, that the in project properties datasources the options are set ok, but QGIS doesn't work as the options show (see also https://github.com/QGEP/QGEP/issues/774).

What to do:
- go to project properties datasources and change the two first options (transaction mode and uncheck EvaluateDefaultValuesOnProviderSide), 
- save the properties (and also the project)
-  then go to project properties datasources and change again  (transaction mode="AutomaticGroups" and check EvaluateDefaultValuesOnProviderSide) (as it looked in the beginning)
-> now I have no more warnings and errors and I can create the records!

**Comment by ponceta** [comment]
@urskaufmann thank you for the check. If you can send me the fixed .qgs file I can update the QGIS project PR.
