### ISSUE TITLE
as range with bigger limits and constraints:

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#31]
Numeric fields with range in vsa-dss: we decided to  use range with bigger limits and constraints: as best
But QGIS works not as expected:
example field ma_dimension1 in vw_tww_wastewater_structure
I define a range 0 to 10000, and a constraint  ("ma_dimension1" <= 4000 and  "ma_dimension1" >= 0) or ( "ma_dimension1"  is  NULL) with enforce the constraint.
Entering 8000 -> white
I delete one "0" -> 800 -> orange
I type the "0" again -> 8000  -> white
I type another "0" -> 80000 -> orange
I select the 80000 and delete -> mm / NULL -> orange (works if I use the black button with x, then its white) 

It's not what I expect! 
PS: in the last project-version, there is an error in the constrait formula

**Comment by sjib** [comment]
@ponceta please (re-)open error report on QGIS repo as discussed today in the technical meeting.

**Comment by urskaufmann** [comment]
reason is: the field is more than once in the attribut form (on different tabs). if a field is just once in the attribut form, the constraints are ok

**Comment by ponceta** [comment]
@urskaufmann that's a good input because it works fine otherwise.

**Comment by ponceta** [comment]
Set as QGIS upstream issue.

**Comment by sjib** [comment]
@ponceta Is this solved in QGIS?

**Comment by cymed** [comment]
Upstream issue is fixed, closing here
