### ISSUE TITLE
More than one oid_prefix can be active at the same time

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#320]
**Describe the bug**
More than one oid_prefix can be active at the same time

**To Reproduce**
1. Go to tww_sys.oid_prefixes
2. Activate another prefix
3. Save
4. Add an entity

**Expected behavior**
User should at least be warn if he activates more than one oid_prefix.

**Screenshots / data**

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**
oid_prefix is set to define who is actually creating entities

**Comment by ponceta** [comment]
As soon as https://github.com/teksi/wastewater/pull/319 is merged, an error will be prompted if your database is not correctly set.

**Comment by sjib** [comment]
solved with https://github.com/teksi/wastewater/pull/319
