### ISSUE TITLE
vw_tww_maintenance should be vw_tww_maintenance_event

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#33]
There are several problems with this vw:
- name should be vw_tww_maintenance_event
- it is now composed of superclass maintenance_event and subclass examination. The other subclasses are missing: maintenance (one field) and bio_ecol_assessment (17 fields).
- the class_prefix for the fieldnames seems to be helapful in this case: EX for examination, BO for bio_ecol_assessment and MN for Maintenance (Unterhalt)

**Comment by sjib** [comment]
That is right!
There is a change between qgep (VSA-DSS 2015) and teksi_wastewater (VSA-DSS 2020).
vw_qgep_maintenance event cannot be just renamed to vw_tww_maintenance_event.

3 subclass views have to be newly designed as we have now three subclasses for maintenance_event and it is not allowed anymore to directly add data to the class maintenance_event (ABSTRACT), but only to the subclasses.

I suggest also to create 3 separate forms, depending of what kind of data I want to add.

**Comment by ponceta** [comment]
According to @3nids PR #40 , this should be now fixed :
@urskaufmann once the PR is merged, the .qgs project need to be adapted.

Preview of how it could look like :
![vw_maintenance_event](https://github.com/teksi/wastewater/assets/8614223/6ecb6a3b-ad9e-4e5b-9cdc-700ea08bdc47)

**Comment by sjib** [comment]
@ponceta maintenance_type = unknown should not be possible to be saved as maintenance_event is ABSTRACT!

**Comment by ponceta** [comment]
> @ponceta maintenance_type = unknown should not be possible to be saved as maintenance_event is ABSTRACT!

- [ ] We can block the user from validating the form with unknown as value.
- [ ] We remove the unkown value, QGIS will automatically set `examination` as the first aphabetical item on the list for any new entry (or a default one set by the user).

What is new in QGIS is that we can use enumerations for postgreSQL types.

Possible client adaptations :

![image](https://github.com/teksi/wastewater/assets/8614223/df078f08-a5b2-4f05-b37d-d5cbba8162fa)
