### ISSUE TITLE
Unit tests on Plugin not working

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#350]
The shell script does no longer find docker-compose.

Run docker-compose run qgis /usr/src/plugin/.docker/run-docker-tests.sh
/home/runner/work/_temp/5e9ea8a8-2b51-43b6-b0d3-170704715baa.sh: line 1: docker-compose: command not found

**Comment by ponceta** [comment]
Solved with https://github.com/teksi/wastewater/pull/363
