### ISSUE TITLE
Interlis-Import and Export: Missing classes

### ISSUE THREAD

**Issue by tomep** [teksi/wastewater#352]
**Describe the bug**

[Wastewater structure_symbol], [wastewater structure_text], [maintenance event_wastewater structure_assoc] and [reach_text] are not imported.
I have carried out an import and export test of my productive data and created a table of the quantity structure. It is clear that the previously mentioned classes are not imported.
![image](https://github.com/user-attachments/assets/0053f786-e7dd-4592-8025-eba90d9d0113)

There seems to be a bug in the class [MaintenanceEvent_WastewaterConstructionAssoc] in particular. As a result, no maintenance events are visible in Teksi.

The flush nozzle class is also not exported.

**To Reproduce**
Exact steps to reproduce the behavior:

1. Import Data
2. These classes are missing in the Object Selection task
![image](https://github.com/user-attachments/assets/8ebeca68-4fa7-4030-bf10-23864ab513e9)

**Expected behavior**

The data import should include all original tables

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by tomep** [comment]
**[MaintenanceEvent_WastewaterConstructionAssoc]:**
Interlis format comparison sample data set DSS vs. my Data.
DSS: 
`<DSS_2020_1_LV95.Siedlungsentwaesserung.Erhaltungsereignis_AbwasserbauwerkAssoc><AbwasserbauwerkRef REF="ch080qwzSW000142"/><Erhaltungsereignis_AbwasserbauwerkAssocRef REF="ch080qwzEH001005"/></DSS_2020_1_LV95.Siedlungsentwaesserung.Erhaltungsereignis_AbwasserbauwerkAssoc>`
My Data: 
`<DSS_2020_1_LV95.Siedlungsentwaesserung.Erhaltungsereignis_AbwasserbauwerkAssoc><AbwasserbauwerkRef REF="ch14734hBW100068"></AbwasserbauwerkRef><Erhaltungsereignis_AbwasserbauwerkAssocRef REF="ch14734hEU180005"></Erhaltungsereignis_AbwasserbauwerkAssocRef></DSS_2020_1_LV95.Siedlungsentwaesserung.Erhaltungsereignis_AbwasserbauwerkAssoc>`

The data is available in the intermediate table (schema "pg2ili_abwasser").
![image](https://github.com/user-attachments/assets/ca8477fd-4941-4885-905c-289597e4706d)

**Comment by sjib** [comment]
Should be all solved - please re-open if needed.
