### ISSUE TITLE
Topology-layers and SQL-Button, error Could not initialize transaction

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#372]
**Describe the bug**
When I click the SQL-button and the TWW-layers are not editable, there is an error:  
CRITICAL    Error : Could not initialize transaction

**To Reproduce**
Exact steps to reproduce the behavior:
1. Start TWW-project
2. Click on TWW-SQL-Button
3. See error

**Expected behavior**
The error-message is not useful for users.
Possible improvements:
- not an error, but a message to the user, that the vw_tww_reach layer should be editable
or
- set the layer editable with click on the SQL- button

**Screenshots / data**
![image](https://github.com/user-attachments/assets/5e9a9b68-031a-497d-8351-cc3e9b91a98e)

**Desktop (please complete the following information):**
 - TWW version 
 - QGIS Version 3.34.4
 - OS Win 10

**Comment by ponceta** [comment]
![image](https://github.com/user-attachments/assets/f0861ccd-5010-485b-a76c-2a0d0e417639)

Fixed
