### ISSUE TITLE
alter pipe profile type to numeric(8.5)

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#39]
code is here
https://github.com/teksi/wastewater/blob/81452e11020352a74090e8e143144de2ccda24fb/datamodel/changelogs/0001/03_tww_db_dss.sql#L820

See issue https://github.com/QGEP/QGEP/issues/830

**Comment by 3nids** [comment]
that should be an easy fix, no?
can we either fix this or mark this issue as won't fix?

**Comment by sjib** [comment]
We cannot fix this as long as it is not fixed in INTERLIS, else we will have a problem on export - I have added it to the issue list at the VSA.

**Comment by 3nids** [comment]
@domi4484 is this really an issue, we cannot handle this on export? i.e. alter the precision on export.

**Comment by cymed** [comment]
Coding-wise it is easy, but the association DNA is a 1:1 mapping of the official model, thus the issue is raised in case someone else finds this problem. We wait with the fix until the next minor release of the VSA model

**Comment by 3nids** [comment]
> 1:1 mapping of the official model

It used to be "where possible, and adapt when required".

So closing this as won't fix for now.
