### ISSUE TITLE
Interlis Update does not update

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#397]
**Describe the bug**

**To Reproduce**
Exact steps to reproduce the behavior:
1. Import a dataset
2. Import into an empty database
3. Duplicate the dataset and alter one attribute (i.e. set all "Baujahr" from 1800 to 1850)
4. Import the altered dataset
5. No alterations are saved

**Expected behavior**
Update.

**Comment by ponceta** [comment]
I can confirm the update is not a feature yet. It only imports what is missing (append only).

This is probably a prio1 for INTERLIS users.

**Comment by sjib** [comment]
We have added these options (update, append, update and append) in the TIT project requirements

**Comment by domi4484** [comment]
The logic was (in theory) not changed since QGep. So if it used to work in QGep I will say its a bug
