### ISSUE TITLE
German project translation - link to transifex project

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#398]
@ponceta Can you update the transifex link so I can tell Tom where to add the translations for the forms?

https://github.com/teksi/wastewater/tree/main/docs

@sjib Danke fürs prompte Feedback.
Ja, die «local»-Einstellungen in QGIS und das Startfile habe ich im gleichen Ordner geöffnet wie die *_de.qm-Datei.
Viele Layer sind auch Deutsch.

Die **Formulareinträge** sind jedoch alle **English**.
Dies fehlt demnach noch, oder?

Grüsse
Tom

Betreff: AW: TWW 20204.0.1 -Deutsch

Nein, das sollte funktionieren, wenn die _de.qm Datei im selben Ordner ist und du die Einstellungen richtig gesetzt hast in QGIS

https://teksi.github.io/wastewater/installation-guide/workstation.html#install-the-demo-project

 
![grafik](https://github.com/user-attachments/assets/2defaf73-6a65-4602-aae4-f69cae22fb51)

![grafik](https://github.com/user-attachments/assets/38ff2640-965a-4217-82ac-ef8c221a977c)

Es ist einfach noch nicht alles übersetzt, erst einzelne Layer.
vw_tww_* zu übersetzen ist etwas kritisch – dann könnte der INTERLIS Import / Export nicht mehr funktionieren.

Vielleicht müsste man den ersten Screenshot auch noch in die Doku einfügen von den Settings.

Betreff: TWW 20204.0.1 -Deutsch

Hallo @sjib 

Ich habe mir grad die neuste Version besorg und gestartet.
Bei der Übersetzung erhalte ich das gleiche Bild wie bei 2024.0.0.
Das ist demnach noch offen?!
Grüsse
Tom

**Comment by urskaufmann** [comment]
All in QGEP_de translated Alias of fieldnames are missing... 
Is it not possible to have them back from QGEP?

And @anybody who translates: be careful with value_en. Do not translate (to value_de), if the translation is for a fieldname!

**Comment by urskaufmann** [comment]
PS: I have translated last week a bigger part of the TWW_Docs, User-guide. But I can not see the changes in the docu. Are there not every night updates for the german docu?

**Comment by sjib** [comment]
> Ich habe mir grad die neuste Version besorg und gestartet.
> Bei der Übersetzung erhalte ich das gleiche Bild wie bei 2024.0.0.
> Das ist demnach noch offen?!
> Grüsse Tom

Feedback von @ponceta 
Der Download-Link im Dokument ist falsch, ich werde es korrigieren.
Dies ist der korrekte Link für alle aktuellen Assets: https://github.com/teksi/wastewater/releases
 
(Deshalb brauchen wir dringend bessere Tools, um alles rund um die Teksi-Module zu installieren 😉 )
 
Die neuesten Projektübersetzungen findest du hier :
 
![project_translatoins](https://github.com/user-attachments/assets/c746f819-ae65-4efe-ab6d-bc3c98d6e4a1)
 
Es gibt noch etwas offen ist der übersetzte Wert in der richtigen Sprache (eigentlich ist es value_en, die zu value_fr oder value_de in Ihrem übersetzten Projekt wechseln sollte.

 
•	Übersetzungen funktionnieren : siehe grün
•	Übersetzungen sind noch zu einsetzen in transifex : siehe gelb -> https://app.transifex.com/teksi/tww-qgis-project/translate/#de/tww-qgis-project/
•	Value lists die noch eine manuelle Änderung brauchen : siehe rot
 
Wenn transifex Übersetzungen verbessert sind kann man diese zum release assets aktualisieren.
![projectranslations_status](https://github.com/user-attachments/assets/71584d06-ad44-4afb-aa18-d6346e8aeabe)

**Comment by sjib** [comment]
Hallo Tom,

Wir haben deine Anfrage zur Teilnahme an der deutschen Übersetzung des Projekts erhalten und angenommen. Du wirst sehen, dass es verschiedene Bereiche gibt (Dokumentation, QGIS-Projekt, Plugin) und dass nach und nach alle TEKSI-Module in dieser Schnittstelle erscheinen werden.

Wie damals bei QGEP werden Übersetzer benötigt, um die Übersetzungen vom Englischen ins Französische oder Deutsche durchzuführen.

Da es sich um ein technisches Gebiet handelt, war es bisher sehr kompliziert, einen globalen Übersetzungsauftrag für das Ganze zu erteilen, weshalb man sich hauptsächlich auf Benutzerbeiträge verlässt.

Der Vorteil dieses Systems ist, dass es sehr einfach ist, eine fehlerhafte Übersetzung „reparieren“ zu gehen.

Wenn du möchtest, kannst du einen Blick auf die Übersetzungen des QGEP-Projekts werfen, um dir ein Bild zu machen! 

https://explore.transifex.com/qgep/


Einen schönen Tag noch!

Arnaud

**Comment by sjib** [comment]
https://app.transifex.com/teksi/ is the link for the transifex project - correct @ponceta

**Comment by urskaufmann** [comment]
zu den "roten": wie schon ein paar mal erwähnt, kann man das im qgs-Projekt auch mit suchen/ersetzen machen (value_en durch value_de ersetzen).  Und im Transifex muss man sehr aufpassen, dass man nicht die Tabellenspaltennamen der vl erwischt. Also man muss immer den Context prüfen!
Aber im Moment sind diese englischen Ausdrücke value_en gar nicht drin im Transifex, Wie auch die gelben Attributbezeichnungen grundsätzlich fehlen. Das war bei QGEP noch anders. Und muss hier auch noch ändern. Wer kann das richtig konfigurieren, dass diese Attributbezeichnungen auch ins Transifex kommen?

**Comment by PeterZamudio** [comment]
This Issue is blocking the migration at the moment. I do hope can be resolved soon.
Even after the translation Fieldnames and lookups are _en
Thank you for your efforts.

**Comment by urskaufmann** [comment]
Doc / User-guide is translated to german to 99%, but does not appear (https://teksi.github.io/wastewater/de/  or where is the tww-docu, not the "dev" version).

**Comment by urskaufmann** [comment]
TWW_QGIS_project: There are all the names of valuelists not translated (but the user normally does not work with these tables, so why translate them).
If I search for "_current" I can't find all the fieldnames with *_current  -->  All fieldnames are missing. 
All value_en are missing. 
The names of the new Layers (vw_tww_reach etc) are translated in Transifex, but do not change in a German qgs.
