### ISSUE TITLE
CI Transifex unavailable

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#406]
**Describe the bug**
CI Transifex unavailable

**To Reproduce**
Propose any modification, CI will fail.

**Expected behavior**
CI of translation is working as expected.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - Continuous Integration
 - Transifex

**Additional context**
External source.

**Comment by sjib** [comment]
https://github.com/teksi/wastewater/issues/398
