### ISSUE TITLE
Transifex: Glossaries missing

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#418]
In QGEP we had Glossaries in Transifex. In TWW they are missing. It should be possible to generate them from value_list_base

**Comment by ponceta** [comment]
We were told by Transifex it is a premium feature not included for open source organizations. 
We have to dig in to see how it was included in QGEP.

**Comment by ponceta** [comment]
We have to dig in to look how to include glossaries in Transifex.

![image](https://github.com/user-attachments/assets/f518e0f8-1f7f-4c4d-869e-2c7fe4391e15)

**Comment by cymed** [comment]
You can download the QGEP glossaries to see how the csv is structured. Ideally, we manage the value list translations on the db side over the same pipeline as the docs

**Comment by cymed** [comment]
Closing, duplicate of #140

**Comment by ponceta** [comment]
https://help.transifex.com/en/articles/6230893-uploading-a-glossary

**Comment by ponceta** [comment]
https://docs.google.com/spreadsheets/d/1qeoCVwdOLyhdLHqVKsOzZ5zyle3iiQd1pVTFKU_rbGU/edit?usp=sharing

Please send me your gmail account address if you want to contribute.
