### ISSUE TITLE
Database default values don't work in QGIS

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#420]
**Describe the bug**
Database default values only work database side but are overwritten by QGIS 

**To Reproduce**
Exact steps to reproduce the behavior:
1. Open TWW QGIS project
2. Define values for fk_provider and fk_dataowner
3. Create a Wastewater structure
4. default fk_provider and fk_dataowner are not displayed
5. Click ok and reopen the same form
6. fk_provider and fk_dataowner are not selected

**Expected behavior**
A user can define default fk_provider and fk_dataowner in QGIS too.

**Screenshots / data**
![image](https://github.com/user-attachments/assets/a630fc91-d2e0-4cfb-abb9-83a6d3016aef)

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by cymed** [comment]
Did you try saving the entries? We only set the default values on od (using tww_app.set_default_values) by using a trigger on tww_od.default_values. So far, we do not set the defaults on app.

**Comment by sjib** [comment]
see also https://github.com/teksi/wastewater/issues/425

**Comment by ponceta** [comment]
Default values have been inserted :

![image](https://github.com/user-attachments/assets/77641aa8-fa10-4a77-ada9-28b04d60e4d4)

But when the db queries it, it returns NULL :

![image](https://github.com/user-attachments/assets/c9a4880b-b691-41de-b543-25c6fe2437d9)

Is it right to call it `BEFORE` the `INSERT`?

My current workaround is to define QGIS variables :

https://github.com/teksi/wastewater/blob/4a9d9bb469c5335bec06b7e822f93cbe833763bf/datamodel/app/functions/organisation_functions.sql#L124-L130

But this will require some project configurations and I would rather have a db working solution.
