### ISSUE TITLE
Datamodel / drainage channels

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#421]
**Describe the bug**
What happens with drainage channels?

**To Reproduce**
What to expect of drainage channels from QGEP?
Hydraulic function is not available anymore and the drainage water is still not available 

**Expected behavior**
Drainage channels and rainwater channels can easily be identified.

**Screenshots / data**
![image](https://github.com/user-attachments/assets/c17a5fbb-9b5c-4083-80d5-691d06998d04)

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by cymed** [comment]
I don't see the problem:

Function hydraulic: tww_vl.channel_function_hydraulic code 145
Usage current: tww_vl.channel_usage_current code 4514

**Comment by ponceta** [comment]
I don't know why I didn't find these at the time I opened this issue... :S
