### ISSUE TITLE
Cut reach does not work

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#422]
**Describe the bug**

**To Reproduce**
Exact steps to reproduce the behavior:
1. Try to cut a reach with QGIS tool
2. See error

```
2024-09-19T15:36:40     CRITICAL    Couche vw_tww_reach : Erreur PostGIS lors de l'ajout d'entité : ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « in_od_reach_point_identifier »
             DETAIL: La clé « (identifier, fk_dataowner)=(HA1339E, ch080qwzPR000018) » existe déjà.
             CONTEXT: instruction SQL « INSERT INTO tww_od.reach_point (
              obj_id
              , elevation_accuracy
              , fk_dataowner
              , fk_provider
              , fk_wastewater_networkelement
              , identifier
              , last_modification
              , level
              , outlet_shape
              , pipe_closure
              , position_of_connection
              , remark
              , situation3d_geometry
              ) VALUES (
              COALESCE( NEW.rp_to_obj_id, tww_app.generate_oid('tww_od'::text, 'reach_point'::text) )
              , NEW.rp_to_elevation_accuracy
              , COALESCE(NULLIF(NEW.rp_to_fk_dataowner,''), NEW.fk_dataowner) -- fk_dataowner
              , COALESCE(NULLIF(NEW.rp_to_fk_provider,''), NEW.fk_provider) -- fk_provider
              , NEW.rp_to_fk_wastewater_networkelement
              , NEW.rp_to_identifier
              , NEW.rp_to_last_modification
              , NEW.rp_to_level
              , NEW.rp_to_outlet_shape
              , NEW.rp_to_pipe_closure
              , NEW.rp_to_position_of_connection
              , NEW.rp_to_remark
              , ST_EndPoint(NEW.progression3d_geometry) -- situation3d_geometry
              ) RETURNING obj_id »
             fonction PL/pgSQL tww_app.ft_vw_tww_reach_insert(), ligne 40 à instruction SQL
```

**Expected behavior**
Reaches can be cut with QGIS standard tools.

![image](https://github.com/user-attachments/assets/e4efe89a-84f7-43d3-8160-a11b96826137)

**Screenshots / data**
![image](https://github.com/user-attachments/assets/4d53f2b2-2042-4925-a88a-7ef736d23b03)

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by cymed** [comment]
Was not implemented in qgep. Potential fix see #142 (WIP, lacking time and funds to continue development)

**Comment by sjib** [comment]
@cymed Can you make an estimate for development?

**Comment by ponceta** [comment]
Yet if you remove the index : in_od_reach_point_identifier it works.

If you edit it without local buffer instead of transaction groups it works if you reconnect the node after splitting (we work with local buffer in Pully)

It should be fixed, the best way would be to finance this cutting tool since cuting reaches is still complex to carry properly.

**Comment by ponceta** [comment]
QGIS has introduced a new default behaviour when copying or dividing an entity, it now uses duplicate field value by default which can be wrong in many cases :

![image](https://github.com/user-attachments/assets/05bd6f5f-378e-4a8c-8f86-50163d59cc9d)

https://github.com/teksi/wastewater/pull/465 Fixes that behaviour.
