### ISSUE TITLE
_usage_current calculation is wrong

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#424]
**Describe the bug**
_usage_current calculation shoud be displaying the dirtiest water type

**To Reproduce**
Exact steps to reproduce the behavior:
1. connect clean wastewater and wastewater reaches to a node
2. See error

**Expected behavior**
dirtiest water type is displayed 

**Screenshots / data**
![image](https://github.com/user-attachments/assets/dad3c1ad-e086-4d05-86b7-378065621bd8)

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by cymed** [comment]
What are your function_hierarchic? Function_hierarchic outweighs usage_current

https://github.com/teksi/wastewater/blob/c7c7e36b71a8bbde9aa1da13dd17347300e74007/datamodel/app/functions/symbology_functions.sql#L112-L116

**Comment by ponceta** [comment]
Ohooo! I didn't knew that! That's a new recommandation?

**Comment by cymed** [comment]
It is actually quite old. Otherwise we'd have problems with swwf connections (where you fill out the effective usage) into pwwf (where you fill out the allowed usage) in cases of wrong connections
