### ISSUE TITLE
Export will fail when drawing new reaches

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#425]
**Describe the bug**
Create a new reach will make the export fails because they don't inherit yet of fk_dataowner and fk_provider which are mandatory for export.

**To Reproduce**
Exact steps to reproduce the behavior:
1. Create a new reach
2. Try to export
3. See error

**Expected behavior**¨
Drawing new reaches does not make the export fail.

**Proposed solution**
Make reach points inherit fk_dataowner and fk_provider from reaches (insert or update) so the export works without too much extra work.

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by cymed** [comment]
If digitised from the main reach view, we do set the values:

```
INSERT INTO tww_od.reach_point (
[...]
)
([...]
fk_dataowner = COALESCE(NULLIF(NEW.rp_to_fk_dataowner,''), NEW.fk_dataowner),
[...]
)
```
if NEW.fk_dataowner should have a default set from `tww_od.default_values`

**Comment by ponceta** [comment]
fk_dataowner and fk_provider are now mandatory so at least this should not be reproduced.

We should have a panel stating if we are production ready. (right know it is only a list of error messages )

![image](https://github.com/user-attachments/assets/cf12e9e5-bb11-411b-bcf5-133c8c2d6c02)

-> set default values

![image](https://github.com/user-attachments/assets/f1ab52a5-c214-4c1e-96ca-36a86dcc6e1a)

-> set oid prefix
