### ISSUE TITLE
Translation QGIS .qgs project sources are not loaded to Transifex due to a CI issue

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#435]
**Describe the bug**
Translation QGIS .qgs project sources are not loaded to Transifex due to a CI issue

**To Reproduce**
Exact steps to reproduce the behavior:
1. Look for example at : https://github.com/teksi/wastewater/actions/runs/11102967845/job/30843916501
2. Most of the layers are not correctly loaded due to an invalide pg setting

**Expected behavior**
Translation QGIS .qgs project sources are successfully loaded to Transifex every time a change occurs on the .qgs project

**Related issue**
 - [ ] #348 
 - [ ] #398
 - [ ] #417

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by urskaufmann** [comment]
wou - thanks. There are now 3110 strings...

Is there any possibility to import the old qgep-translations or to import translations from the tww_sys.dictionary_od_field??? This would save a lot of work and prevent many typo's....
