### ISSUE TITLE
re_building_group_disposal has only a primary key column

### ISSUE THREAD

**Issue by 3nids** [teksi/wastewater#47]
schemaspy spotted this issue

is this expected?

**Comment by sjib** [comment]
No, this is a mistake - I will fix it

**Comment by ponceta** [comment]
An `id` can sometimes be a good thing to have. (automated serial id not NULL would be sufficient)
An `obj_id` is maybe too much (do we consider the link between two objects as an object?)
On the tecnical part, the combination of both fk_ keys is sufficient as primary key and adding not NULL and reference constraints on both fk fields is a good way to go.

**Comment by 3nids** [comment]
In a pure DB vision, a single primary key is useless as we could use compound keys on the 2 reference columns.
But QGIS needs a primary key in a layer to work properly.

And yes, please use a UUID (not necessarily a TWW OID, a simple auto generated UUID is fine) as it is much more robust than serials.

**Comment by sjib** [comment]
@3nids So how should this be then adapted with an UUID? I suggest to then not name it obj_id but uuid_id

`CREATE TABLE tww_od.re_building_group_disposal
(
   obj_id varchar(16) NOT NULL,
   CONSTRAINT pkey_tww_od_re_building_group_disposal_obj_id PRIMARY KEY (obj_id)
)
WITH (
   OIDS = False
);
CREATE SEQUENCE tww_od.seq_re_building_group_disposal_oid INCREMENT 1 MINVALUE 0 MAXVALUE 999999 START 0;
 ALTER TABLE tww_od.re_building_group_disposal ALTER COLUMN obj_id SET DEFAULT tww_sys.generate_oid('tww_od','re_building_group_disposal');
COMMENT ON COLUMN tww_od.re_building_group_disposal.obj_id IS 'INTERLIS STANDARD OID (with Postfix/Präfix), see www.interlis.ch';`

**Comment by 3nids** [comment]
if not already install we need `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";``

and then you can use `uuid_generate_v1()` as default.

**Comment by ponceta** [comment]
If there's no preference, I would go with **uuid_generate_v4 ()** 
```
uuid_generate_v4 () → uuid
Generates a version 4 UUID, which is derived entirely from random numbers.
```
MAC adress are considered as personnal data and I would rather avoid anything to do with RGPD in that context...

**Comment by sjib** [comment]
Does this look good - I just created a table uuidtest:
`CREATE TABLE IF NOT EXISTS test.uuidtest`
`(`
`    id uuid NOT NULL DEFAULT uuid_generate_v4(),`
`    CONSTRAINT uuidtest_pkey PRIMARY KEY (id)`
`)`
`

**Comment by 3nids** [comment]
yes

**Comment by cymed** [comment]
looks good to me. Associations should not require OIDs

**Comment by sjib** [comment]
Solved with https://github.com/teksi/wastewater/pull/49
