### ISSUE TITLE
Curve is not imported correctly

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#474]
**Describe the bug**
Curve is not imported correctly

![image](https://github.com/user-attachments/assets/918ffb7a-2679-4b9b-ac87-b59c971b6118)

Same import works on QGEP :

![image](https://github.com/user-attachments/assets/20db5a64-940c-435e-a659-2d77149ef58d)

**To Reproduce**
Exact steps to reproduce the behavior:
1. Import VSA DSS Testdata
2. See error

**Expected behavior**
Curved elements are imported correctly

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version
 - OS

**Additional context**

**Comment by sjib** [comment]
I cannot confirm!

Did you import: https://github.com/teksi/wastewater/pull/467/files

Can someone else test? If not ok my adaptions in are wrong.

This is my import today with the edit for the VSA:
![grafik](https://github.com/user-attachments/assets/e072fd89-a69d-49e3-a6d9-a00b6f3780e3)

**Comment by ponceta** [comment]
Wrong file indeed! works nice thank you!
