### ISSUE TITLE
Loosing coordinates on INTERLIS Import in classes cover, wastewater_node and reach_point when attribute lage / sohlenkote is missing

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#475]
**Describe the bug**
_A clear and concise description of what the bug is._

INTERLIS Import with dataset that has missing attributes deckel.kote, abwasserknoten.sohlenkote and/or haltungspunkt.kote
The objects with no z attribute are not getting a value in cover.situation3d_geometry, wastewater_node.situation3d_geometry and reach_point.situation3d_geometry

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**
_A clear and concise description of what you expected to happen._

situation3d_geometry is always filled in and not ommited even if z coordinate is not in object of imported dataset

**Screenshots / data**
_If applicable, add screenshots or data to help explain your problem._

Example dataset wastewater_node with geometry (lage) and cote (kote)
![ak_mit_geom_und_sohlenkote_1 2212_vergleich_xtf](https://github.com/user-attachments/assets/e7d1b40c-2d3a-4ee2-849d-067834c141de)

Example dataset wastewater_node with geometry (lage) and without cote (kote)
![ak_ohne_geom_und_sohlenkote_1 2226_vergleich_xtf](https://github.com/user-attachments/assets/4e5656c4-bed5-4a20-8684-15b968559298)

Examples dataset cover with geometry (lage) and without cote (kote)
![deckel_ohne_geom_8 2527](https://github.com/user-attachments/assets/e849c24e-9d41-45e3-a9f1-0272a59e431a)
![deckel_ohne_geom_8 2527_vergleich_xtf](https://github.com/user-attachments/assets/2ce0ebc5-09be-4f35-a46e-258e06f7ed45)

Same with reach_points

**Desktop (please complete the following information):**
 - TWW version 2024.0.2 / 2024.0.3
 - QGIS Version 3.34.8
 - OS Windows 10

**Additional context**

**Comment by sjib** [comment]
It looks like the ST_Force3D funktion is not working as expected if the z parameter is not provided:

![deckel_ohne_geom_1 1064_vergleich_xtf](https://github.com/user-attachments/assets/4bb9b8dc-5fe1-476b-82d8-f996e4925df3)

wastewater\plugin\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py (3 Treffer)

	Zeile 1940:                 situation3d_geometry=self.session_tww.scalar(ST_Force3D(row.lage, row.kote)),
	Zeile 1972:                 situation3d_geometry=self.session_tww.scalar(ST_Force3D(row.lage, row.sohlenkote)),
	Zeile 2082:                 situation3d_geometry=self.session_tww.scalar(ST_Force3D(row.lage, row.kote)),

@ponceta can you check on this? That is a very critical error.

**Comment by sjib** [comment]
![grafik](https://github.com/user-attachments/assets/fbe3fbe8-eb40-488a-95e6-c67c92ad6d9f)

**Comment by sjib** [comment]
This creates problems with network following: https://github.com/teksi/wastewater/issues/456

**Comment by sjib** [comment]
https://postgis.net/docs/ST_Force_3D.html

**Comment by ponceta** [comment]
Try `SELECT ST_FORCE3D(ST_GeomFromText('POINT(2540642.81 1151868.287)',2056),NULL)`

Result is **NULL**, therefore there is no error message since it is the "right" result postgis side

When NULL or empty, we should use `'nan'`

This returns the 3`SELECT ST_FORCE3D(ST_GeomFromText('POINT(2540642.81 1151868.287)',2056),'nan')`

Result is POINT Z (2540642.81 1151868.287 NaN)

So with a coalesce postgis side it would be something like :

`SELECT ST_ASTEXT(ST_FORCE3D(ST_GeomFromText('POINT(2540642.81 1151868.287)',2056),(COALESCE (NULL,'NaN'))::numeric))` Where NULL would be the attribute value `row.kote`, `row.sohlenkote`

**Comment by ponceta** [comment]
Another this is that as long as we allow NULL values for nodes geometries, this is considered as not a bug on any step of the process.

NULL geometries on nodes make the network following functions crash.

**Comment by urskaufmann** [comment]
I had the same problem, 800 nodes without geometry because bottom_level is NULL. Did unload release 2024.03, in release 2024.02 the import of the nodes work as expected

**Comment by ponceta** [comment]
https://trac.osgeo.org/postgis/ticket/5804#comment:1 Raised to postgis community too.

**Comment by ponceta** [comment]
@urskaufmann can you check if it fixes the issue for you too with this fixed version of the plugin :

https://github.com/teksi/wastewater/actions/runs/11608981159/artifacts/2127277991
