### ISSUE TITLE
tww_sys.disable_symbology_triggers() function missing – import in teksi_wastewater plugin fail

### ISSUE THREAD

**Issue by drioeagel** [teksi/wastewater#488]
**Describe the bug:**
The function tww_sys.disable_symbology_triggers() is missing in the PostgreSQL database. When attempting to run SELECT tww_sys.disable_symbology_triggers(); within the teksi_wastewater plugin, an error is thrown indicating that the function does not exist. This prevents the expected deactivation of symbology triggers within the schema tww_sys.

**To Reproduce Exact steps to reproduce the behavior:**
- Open QGIS and load the teksi_wastewater plugin.
- Attempt to perform an import operation that requires disable_symbology_triggers.
- Observe the error message regarding the missing function.

**Expected behavior:**
The disable_symbology_triggers function should exist in the tww_sys schema and successfully disable any relevant symbology triggers without errors.

**Screenshots / data image:**
![image](https://github.com/user-attachments/assets/9ff28f03-1460-45ce-94c7-fcd617754b29)

**Desktop (please complete the following information):**
TWW version: [2024.0.3](https://github.com/teksi/wastewater/releases/tag/2024.0.3)
QGIS Version: 3.34.10-Prizren
OS:

**Additional context:** 
The teksi_wastewater plugin currently relies on the function tww_sys.disable_symbology_triggers() to deactivate certain triggers within the database schema tww_sys. However, this function was not found in the database structure, causing the import functionality to fail. A temporary workaround involves creating the function manually, but a permanent fix is needed within the plugin or the database schema.

**Comment by cymed** [comment]
You probably use an old version of the plugin. [2024.0.3](https://github.com/teksi/wastewater/releases/download/2024.0.3/teksi_wastewater.0.0.0.zip) does not include `tww_sys.disable_symbology_triggers()`

**Comment by drioeagel** [comment]
Thank you for the hint! I’ve now updated the plugin to version 2024.0.3, and it’s indeed working as expected. Thanks for the quick support!
