### ISSUE TITLE
Shortcuts in dict_od_tables and as prefix for attribute-names in views

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#489]
**Describe the bug**
In two cases we have different shortcuts for tables in dict_od_tables and in the vw_tww-tables:
For channel is "CL" in dictionary, but "ch" in your views (was already in QGEP like this).
For biol_eco_assessment is "BO" in the dictionary, but "ba" in your views.

Suggestion: Change the english shortcuts in the dict_od_tables to CH and BA instead of CL and BO.

**Comment by sjib** [comment]
Yes, I have to make the changes in the creation of the dictionary tables if we want to change that.

 

BA is the shortcut_en for Class Badestelle (in qgep), so we should not change that to stay with unique shortcuts per language.

CL -> CH for Channel would be possible. 

 

@ponceta How much effort is it to change the view?

 

I suggest a general principle (to be integrated in the Developers guides): Views should be developed based on the sys dictionaries on not the other way round else we loose control over used shortcuts

**Comment by ponceta** [comment]
This should be no big deal to adapt views in consequence. Better do it before any official release is published.

**Comment by sjib** [comment]
@urskaufmann @ponceta ok like this? If yes I will make a patch for qgep also

**Comment by sjib** [comment]
- [ ] Add requirement to the Developers Guide to use official shortcut_en from Dictionary table in view creation

**Comment by ponceta** [comment]
Were are these official shortcut defined (except in the code of dictionary tables)

**Comment by sjib** [comment]
![tww_sys dictionary_od_table](https://github.com/user-attachments/assets/6f45d023-45ca-4b12-af74-f391dce03fa7)
