### ISSUE TITLE
Unable to Install Plugin - Invalid QGIS Python Extension teksi_wastewater_plugin_dev.zip

### ISSUE THREAD

**Issue by drioeagel** [teksi/wastewater#492]
**Describe the Bug** 
When attempting to install the teksi_wastewater_plugin_dev.zip plugin for testing the AG-64/96 extension in TWW, QGIS displays an error message indicating that the ZIP file is not a valid QGIS Python extension. The message states: "The ZIP file is not a valid QGIS Python extension. No root directory was found."

**To Reproduce Steps to reproduce the behavior:**
1.  Open QGIS.
2.  Go to Plugins > Manage and Install Plugins.
3. Attempt to install the teksi_wastewater_plugin_dev.zip file by selecting Install from ZIP.
4. See error message.

**Expected Behavior** 
The plugin should install successfully without any error messages, allowing testing of the AG-64/96 extension in TWW.

**Screenshots / Data**
![grafik](https://github.com/user-attachments/assets/8d2aff16-725d-4445-9597-834827e8efa2)

**Desktop Information:**

TWW Version: 2024.0.3
QGIS Version: 3.34.10-Prizren
OS

**Comment by cymed** [comment]
You need to extract the zip inside teksi_wastewater_plugin_dev.zip
