### ISSUE TITLE
renaming of attributes 

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#5]
Some type names have typos or can be translated more precisely

| current | new |
| ---------- | --------- |
| tww_od.measure.year_implementation_effectiv | tww_od.measure.year_implementation_effective |
| tww_od.catchement_area_totals | tww_od.catchment_area_totals |
| tww_od.catchement_area_totals.surface_imp_red | tww_od.catchment_area_totals.surface_imp |
| tww_od.catchement_area_totals.surface_imp_red | tww_od.catchment_area_totals.surface_imp |
| tww_od.farm.areable_surface| tww_od.farm.arable_surface |
| tww_od.farm.muck_hill_area_current | tww_od.farm.dung_heap_area_current |
| tww_od.farm.muck_hill_area_planned | tww_od.farm.dung_heap_area_planned |
| tww_od.special_structure.function.bolders_bedload_catchement_dam | tww_od.special_structure.function.bedload_trap |

**Comment by sjib** [comment]
@cymed this is twice?
| tww_od.catchement_area_totals.surface_imp_red | tww_od.catchment_area_totals.surface_imp |

**Comment by sjib** [comment]
and I added 
| tww_od.special_structure.function.bolders_bedload_catchement_dam | tww_od.special_structure.function.bedload_trap |

**Comment by cymed** [comment]
> @cymed this is twice? | tww_od.catchement_area_totals.surface_imp_red | tww_od.catchment_area_totals.surface_imp |

yes it is twice

**Comment by sjib** [comment]
Additional typo: https://github.com/teksi/wastewater/issues/27

**Comment by cymed** [comment]
#5 done with #8
