### ISSUE TITLE
Project: missing adaptions for release 2024.04

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#501]
**Describe the bug**
The shortcut for bio_ecol_a... is now bo instead of ba. The configuration of the attribut form has to be redone and the translation has to be redone (is now not ready for translation, the bo_* terms are missing...)

I can do the translation with download and upload in transifex. But are there other terms of the actual project missing?

**Desktop (please complete the following information):**
 - TWW version 2024.04
 - QGIS Version 3.34.12
 - OS Win 10

**Comment by sjib** [comment]
I guess this is something for 2024.1

**Comment by ponceta** [comment]
https://github.com/teksi/wastewater/releases/tag/2024.0.5 Fixed, we only have to refresh translations according to the new namings.

**Comment by ponceta** [comment]
![image](https://github.com/user-attachments/assets/32d92e81-5561-4c25-93e6-0ce95b8d769c)
