### ISSUE TITLE
Project: transaction groups

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#51]
Standard for transaction mode was automatic transactiongroups.
With this option, the later loaded layers (e.g. vw_tww_overflow, vw_tw_maintenance_event) do not toggle editing as the other layers.
If I change to buffered transactiongroups, all layers do toggle.

Which is the "correct" (best) option? Why are some layers not in the same automatic group as others?

**Comment by ponceta** [comment]
I avoid transaction groups as much as possible so I won't be able to answer this :(

**Comment by 3nids** [comment]
I think we should stick to automatic.
They are not turn into editing because the source definition is not exactly the same. You need to manually edit the project file and adapt the source (sometimes it's just ssl preference which is different).

**Comment by urskaufmann** [comment]
Thanks, That's it. I have to define my Postgis-Connection with SSL-Modus = bevorzugen, then there is no "sslmode" in the qgs-File (as the preconfigured layers). I will add this point in the developers guide
