### ISSUE TITLE
vw_change_points did never work

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#59]
vw_change_point did never work for me, not in qgep and it actually works not in tww.
the following sql-code works now. It shows the wastewater_nodes between reaches with the same channel and with the attributes you can visualize, of the there is a change in material, in clear_height and or in slope. 
I think it's good to have this vw in the database and optional in the project (users have to load themselves).

CREATE OR REPLACE VIEW tww_app.vw_change_points
 AS
 SELECT ne_node.obj_id,
    node.situation3d_geometry AS geom,
    re.material <> re_next.material AS change_in_material,
    re.clear_height <> re_next.clear_height AS change_in_clear_height,
    (rp_from.level - rp_to.level) / re.length_effective - (rp_next_from.level - rp_next_to.level) / re_next.length_effective AS change_in_slope
   FROM tww_od.reach re
     LEFT JOIN tww_od.reach_point rp_to ON rp_to.obj_id::text = re.fk_reach_point_to::text
     LEFT JOIN tww_od.reach_point rp_from ON rp_from.obj_id::text = re.fk_reach_point_from::text
     LEFT JOIN tww_od.wastewater_networkelement ne_node ON ne_node.obj_id::text = rp_to.fk_wastewater_networkelement::text
     LEFT JOIN tww_od.wastewater_node node ON node.obj_id::text = ne_node.obj_id::text
     LEFT JOIN tww_od.reach_point rp_next_from ON rp_next_from.fk_wastewater_networkelement::text = ne_node.obj_id::text
     LEFT JOIN tww_od.reach re_next ON rp_next_from.obj_id::text = re_next.fk_reach_point_from::text
     LEFT JOIN tww_od.reach_point rp_next_to ON rp_next_to.obj_id::text = re_next.fk_reach_point_to::text
     LEFT JOIN tww_od.wastewater_networkelement ne ON re.obj_id::text = ne.obj_id::text
     LEFT JOIN tww_od.wastewater_networkelement ne_next ON re_next.obj_id::text = ne_next.obj_id::text
  WHERE ne_next.fk_wastewater_structure::text = ne.fk_wastewater_structure::text;

**Comment by sjib** [comment]
@urskaufmann Shall we change this in https://github.com/teksi/wastewater/blob/main/datamodel/app/view/vw_change_points.sql ? 
Or are this two different views to keep?

**Comment by urskaufmann** [comment]
yes, please change. Thanks

**Comment by cymed** [comment]
fixed with #366

**Comment by sjib** [comment]
@urskaufmann Does the VSA Transferdatensatz show any results in the vw_change_points. Or does it only display a point if we have two reaches in one channel?

If I open the view it is empty in Release 2024.0.2

**Comment by urskaufmann** [comment]
Yes, there is no point in Transferdatensatz. There is only a point, if there are two reaches with the same channel and if there is a wastewater_node between, so normaly only in PAA-network

**Comment by sjib** [comment]
So if there is a manhole inbetween it is not considered a change as listed in SIA405 Baujahrswechsel, Materialwechsel, Gefällsbruch? 
Or is this view not supporting that visualisation?

**Comment by urskaufmann** [comment]
If there is a manhole, you have the manhole-symbol, that shows, where reaches end/start. There is not a different symbol, if there is a attribut-change. If there is no manhole, you have nothing specific that shows this start-/endpoint...
