### ISSUE TITLE
SingleInheritance views use default obj_id of parent instead of child

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#65]
If the Primary Key of a SingleInheritance view (i.e. tww_app.vw_cover) is missing, the insert command from pirogue uses the PK of the parent (i.e. structure_part). It would be more user friendly to use the child's PK.

**Comment by sjib** [comment]
This should be the same, subclasses should have the same PK as their superclass.

**Comment by cymed** [comment]
If you add a cover in vw_cover, we use `tww_sys.generate_oid('tww_od'::text, 'cover'::text) ` as a default for the view. This default is only applied in three cases:

1. When QGIS is set to apply defaults on provider side
2. when creating an item with an insert query that omits setting obj_id
3.  when creating an item with an insert query that sets obj_id=DEFAULT.

However, when creating an item with obj_id =NULL, we use  `tww_sys.generate_oid('tww_od'::text, 'structure_part'::text)` . The same goes with all SingleInheritance views.

**Comment by sjib** [comment]
I see the problem:
`ww_sys.generate_oid('tww_od'::text, 'structure_part'::text)` will generate an obj_id with prefix + shortcut of structure_part and then 6 digits - eg. `ch000000SP000001`
`tww_sys.generate_oid('tww_od'::text, 'cover'::text)` will generate an obj_id with prefix + shortcut of cover and then 6 digits - eg. `ch000000CO000001`

**Comment by cymed** [comment]
Solve in bugfixing, maybe upstream in pirogue

**Comment by ponceta** [comment]
To be discussed with @ponceta and @3nids

**Comment by ponceta** [comment]
> However, when creating an item with obj_id =NULL, we use `tww_sys.generate_oid('tww_od'::text, 'structure_part'::text)` . The same goes with all SingleInheritance views.

Could you add a bit of context? Is it a case when you insert data with QGIS?

The QGIS project should be set so that the obj_id get generated right but I'm open to enhancements on that side!

**Comment by sjib** [comment]
@cymed Can you show, where this happens in the code?

**Comment by cymed** [comment]
It happens in pirogue, called in https://github.com/teksi/wastewater/blob/1906faba36314b24f61238902856025942351287/datamodel/app/create_app.py#L118-L126

in pirogue, I suppose we enter the exception in https://github.com/opengisch/pirogue/blob/9cbf10f2a8811d84b2051b6b1d2a9c2b78b4a4bb/pirogue/single_inheritance.py#L77-L80 but I can't see why

**Comment by 3nids** [comment]
fixed by #288 

for more details, see https://github.com/opengisch/pirogue/pull/34
