### ISSUE TITLE
Testing INTERLIS Import - fk error reach_point

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#73]
**Describe the bug**
When import the testdataset plugin/teksi_wastewater/tests/data/test-dataset-DSS.xtf I get fk relation errors on reach_point

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'INTERLIS Import'
2. Select and Import 'test-dataset-organisations.xtf'
3. Import is successful
4.  Go to 'INTERLIS Import'
5. Select and Import 'test-dataset-DSS.xtf'
6. See error

**Expected behavior**
These relationship errors should not happen

**Screenshots / data**
![import_test-dataset-DSS xtf4_error_fk](https://github.com/teksi/wastewater/assets/1265865/93ba28ab-cdda-422d-9b6d-801dabaa1176)

**Desktop (please complete the following information):**
 - TEKSI plugin version: Testing version
 - TEKSI datamodel version: https://github.com/teksi/wastewater/actions/runs/7462082294/artifacts/1156824825
 - TEKSI project file version: https://github.com/teksi/wastewater/files/13922071/teksi_wastewater.zip
 - QGIS Version: 3.28.4
 - OS: Windows 10
 - Postgres: PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
 - Postgis: POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.4.3 (Internal)"

**Additional context**
@domi4484 How can I check if the database dump used has the latest improvements you made with  DEFERRABLEin the  datamodel?
 - TEKSI datamodel version: https://github.com/teksi/wastewater/actions/runs/7462082294/artifacts/1156824825

**Comment by 3nids** [comment]
link has been updated with last build

**Comment by sjib** [comment]
With the new version https://github.com/teksi/wastewater/actions/runs/7527102839/artifacts/1169395760 provided I was successful:

![import_test-dataset-DSS xtf_new_version_ok](https://github.com/teksi/wastewater/assets/1265865/23b71004-4207-4cf1-b7ba-dd08a0e4346a)

So I will send out the invitation for testing.
