### ISSUE TITLE
Datamodel tool not loading

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#77]
**Describe the bug**
When enabling admin mode, the datamodel tool is not found

**To Reproduce**
Exact steps to reproduce the behavior:
1. Enable Admin Mode
2. Restart
3. Datamodel Tool not shown

**Expected behavior**
Show datamodel tool gui

**Screenshots / data**
None

**Desktop (please complete the following information):**
see #76 
 
**Additional context**

**Comment by domi4484** [comment]
The datamodel tool is not included. As I undestood it should be implemented as a separate module for all teksi plugins in a second step.

**Comment by cymed** [comment]
> The datamodel tool is not included. As I undestood it should be implemented as a separate module for all teksi plugins in a second step.

Ok. Closing issue
