### ISSUE TITLE
Possibility to export from command line missing

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#78]
With the old qgepqwat2ili, there was the option to export from the command line. As far as I can see, the corresponding function in TEKSI wastewater is missing

**Comment by domi4484** [comment]
The import export is now integrated in the plugin and is not a separate module anymore.
It is possible to re-add a script in the plugin directory to import/export from command line. Is it needed for automated tasks?

**Comment by cymed** [comment]
> The import export is now integrated in the plugin and is not a separate module anymore.
> It is possible to re-add a script in the plugin directory to import/export from command line. Is it needed for automated tasks?

It is. Multiple service providers need to deliver their datasets to i.e. the canton on a regular basis

**Comment by cymed** [comment]
If possible within the scope of your contract, it would be preferrable to pass a --qgs-file instead of --labels-file from where the labels are extracted

**Comment by domi4484** [comment]
I have added a draft of a CMD Tool to import/export. But i noticed since I changed the implementation to use the Java il tools, we have now a dependency on the QGIS classes which are not available in every python environment.
Is that acceptable? I can imagine that those are not provided on most servers where the script is run?
May be an alternative to package the script in a docker image?
Otherwise some rewrite of the logic to gather the Ilitools would be needed.

> If possible within the scope of your contract, it would be preferrable to pass a --qgs-file instead of --labels-file from where the labels are extracted

Same as above, extracting the labels from the project needs the QGIS classes (mostly processing) to be available. Maybe because of this limitations was it done with the labels-file?

**Comment by sjib** [comment]
- [ ] @cymed connects with Sandro
- [ ] Feedback here what is need
- [ ] implement by @domi4484

**Comment by ponceta** [comment]
Could we have a template syntax script for this commandline query using QGIS dependancies?

**Comment by cymed** [comment]
I just connected with Sandro. They use the current batch script in a windows environment without QGIS installation, but as long as the problem can be solved by installing QGIS somewhere accessible and altering PYTHONPATH, it should be manageable.

From a GDI point of view, wrapping the export in a docker image is probably a good way forward mid-term. I am however hesitant to start dockerising the interlis import/export without a clear project definition. 

@domi4484 I suggest the following

- [ ] Integrate import/export based on the assumption that a QGIS Desktop installation with the TEKSI wastewater plugin is available in the environment from which the shell script is run
- [ ] document the dependencies of the necessary QGIS Classes and Libraries in the new docs
- [ ] document the syntax in the new docs

As we assume the QGIS Desktop installation with the TEKSI wastewater plugin to be available, there is no advantage on the user side to define the --labels-file instead of the --qgs-file. 

@ponceta Should we add the idea of a dockerised import/export gateway to the harmonsiation pendencies? If we are to follow that path, we should do so for all TEKSI modules.
