### ISSUE TITLE
Layer vw_network_node and vw_network_segment not available

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#79]
**Describe the bug**
Perhaps I have these layer not available when opening the project the first time, because I did install the database with a bat-file from 
tww_dev_structure_with_value_lists.sql
I have to run manually
REFRESH MATERIALIZED VIEW tww_app.vw_network_node; REFRESH MATERIALIZED VIEW tww_app.vw_network_segment;
**To Reproduce**

**Expected behavior**
These 2 lines of sql should run automaticaly.

**Screenshots / data**
-
**Desktop (please complete the following information):**
 - TEKSI plugin version 0.0.0
 - TEKSI datamodel version testversion 24.01.15
 - TEKSI project file version 24.01.15
 - QGIS Version - see the About menu 3.28.6
 - Postgres - you can check with `SELECT version();` 14.5
 - Postgis - you can check with `SELECT PostGIS_full_version();` 3.3.2
 - OS win10
 

**Additional context**

**Comment by sjib** [comment]
I just clicked on the button "SQL" - this should also refresh.
But I agree, why not add the command `REFRESH MATERIALIZED VIEW tww_app.vw_network_node; REFRESH MATERIALIZED VIEW tww_app.vw_network_segment;` at the end of the import script.

**Comment by sjib** [comment]
Discuss together with https://github.com/teksi/wastewater/issues/75 Main cover / main node

**Comment by sjib** [comment]
@domi4484 We discussed this in the technical group on Tuesday.
Please add the following queries to run at the end of the import process - I think that would be user friendly:

`REFRESH MATERIALIZED VIEW tww_app.vw_network_node;`
`REFRESH MATERIALIZED VIEW tww_app.vw_network_segment;`

**Comment by sjib** [comment]
See #75 for implementation

**Comment by 3nids** [comment]
should be fixed in last plugin demo, please re-open if needed
