### ISSUE TITLE
  Error : No supported model was found among '['SIA405_Base_Abwasser_LV95']'

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#80]
Got this error when importing vsa_organisationen_testdatensatz.xtf

**Comment by sjib** [comment]
@urskaufmann you have to take the 2020_1 version: https://www.vsa.ch/models/organisation/vsa_organisationen_2020_1.xtf

**Comment by domi4484** [comment]
I have made a sligthly better error text in case there is only one model in the xtf: [cd9db02](https://github.com/teksi/wastewater/pull/23/commits/cd9db02fd7c5cd52e97ac3247759c317fe8ed6a8)

Supported import model are:
- VSA_KEK_2020_1_LV95
- SIA405_ABWASSER_2020_1_LV95
- SIA405_Base_Abwasser_1_LV95
- DSS_2020_1_LV95
