### ISSUE TITLE
new function set dataowner / provider

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#86]
nobody, really nobody wants to edit the attribut dataowner and provider in all of the 47 classe of the DSS, that have these attributes.
imo it's wrong to have dataowner in tables like reach_point (no reach_point without reach) or structure_part (no structure_part without wastewater_structure). But it's like that...
And it's not possible to export a correct xtf-file with NULL in these fields. So we have to find a simple way to fill in all these values.

Suggestion: create a tool, where the user can define a default organisation for dataowner and another one for provider. With start, all records in all tables "where fk_dataowner is NULL" will be updated with default dataowner, where "fk_provider is NULL" will be updated with default provider. 
That's it. The user can change this value manually and he decides when to use this tool.

There are 46 classes with a dataowner:

2 | wastewater structure | Abwasserbauwerk
3 | waste water treatment | Abwasserbehandlung
5 | wastewater networkelement | Abwassernetzelement
8 | connection object | Anschlussobjekt
9 | waste water treatment plant | Abwasserreinigungsanlage
13 | structure part | Bauwerksteil
16 | throttle shut off unit | Absperr-/Drosselorgan
19 | catchment area | Einzugsgebiet
32 | reach point | Haltungspunkt
33 | hq relation | HQ-Relation
36 | hydraulic geometry | Hydro-Geometrie
37 | hydr geom relation | Hydro-Geometrie-Relation
42 | measurement series | Messreihe
43 | measurement result | Messresultat
44 | measuring point | Messstelle
46 | surface runoff parameters | Oberflächenabflussparameter
47 | organisation | Organisation
49 | pipe profile | Rohrprofil
53 | retention body | Retentionskörper
55 | sludge treatment | Schlammbehandlung
63 | overflow | Überlauf
64 | overflow characteristic | Überlaufcharakteristik
70 | mechanical pretreatment | Mechanische Vorreinigung
74 | mesure | Massnahme
99 | measuring device | Messgeräät
105 | zone | Zone
108 | wwtp energy use | ARA Energienutzung
111 | maintenance event | Erhaltungsereignis
2723 | control center | Steuerungszentrale
2964 | profile geometry | Rohrprofil Geometrie
3705 | damage | Schaden
3754 | file | Datei
3776 | data media | Datenträger
5100 | log card | Stammkarte Sonderbauwerk
5105 | catchement area totals | Einzugsgebiet / Wassermengen / Einleitstelle
5107 | hydraulic characteristic data | Hydraulische Kennwerte
6100 | building group | Gebäudegruppe
6101 | farm | Landwirtschaftsbetrieb
6105 | building group baugwr | Gebäudegruppe BAUGWR
6106 | disposal | Entsorgung
9998 | mutation | Mutation
99980 | TEXT | Text
99981 | SYMBOL | Symbol
99982 | maintenance event wastewater structure | Erhaltungsereignis Abwasserbauwerk
99985 | building group disposal | Gebaeudegruppe Entsorgung
99986 | progression alternative | Alternativ Verlauf

**Comment by cymed** [comment]
I am building a import/export gateway for AG-96 with @el-wiss which has the same problem. My workaround is 

-- 
CREATE TABLE IF NOT EXISTS {ext_schema}.vsadss_dataowner (
	onerow_id bool PRIMARY KEY DEFAULT true -- in Kombi mit Constraint verhindert der pkey, dass mehr als 1 Datenherr genutzt wird
	,obj_id varchar(16) NOT NULL
	, CONSTRAINT onerow_uni CHECK (onerow_id));

And updating it using

INSERT INTO  {ext_schema}.vsadss_dataowner (obj_id) VALUES ('foo') 
ON CONFLICT ON CONSTRAINT onerow_uni DO UPDATE set obj_id=EXCLUDED.obj_id

The table will always have a maximum of one entry.
