### ISSUE TITLE
Interlis Import only works when the user owns all triggers

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#87]
**Describe the bug**
Interlis Import only works when the user owns all triggers, otherwise drop_symbology_functions runs into an error

**To Reproduce**
Exact steps to reproduce the behavior:
1. Alter Ownership of one trigger to another user (i.e. on_reach_point_update)
2. Try Import
3. See error

**Expected behavior**
Import working

**Screenshots / data**
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) must be owner of relation reach_point CONTEXT:  SQL statement "DROP TRIGGER IF EXISTS on_reach_point_update ON tww_od.reach_point" PL/pgSQL function tww_sys.drop_symbology_triggers() line 3 at SQL statement [SQL: SELECT tww_sys.drop_symbology_triggers();] (Background on this error at: https://sqlalche.me/e/14/f405) 

**Desktop (please complete the following information):**
- TEKSI plugin version: dev
 - TEKSI datamodel version: dev
 - TEKSI project file version: 2024_01_15
 - QGIS Version - see the About menu: 3.28.11
 - Postgres: 12.17
 - Postgis: POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"
 - OS: Windows

I deleted the statement timeout option temporarily (see #76)

**Additional context**

**Comment by cymed** [comment]
Why do we drop the symbology triggers instead of disabling and re-enabling them anyway?

**Comment by cymed** [comment]
To be solved by #88. Changes tested.

**Comment by sjib** [comment]
Reopened - as not yet merged

**Comment by 3nids** [comment]
should be fixed in last plugin demo, please re-open if needed
