### ISSUE TITLE
translation files missing

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#90]
Do we already have the .qm files somewhere?

**Comment by cymed** [comment]
Language dependencies and handling is in the scope of Part 1 (Point 2.4 in Cahier des charges)

**Comment by sjib** [comment]
@3nids Please check as discussed today how qm files work with the qgz format and provide it with the project

**Comment by 3nids** [comment]
translations are now available as artifacts of these builds: https://github.com/teksi/wastewater/actions/workflows/project-translation.yml
