### ISSUE TITLE
pg_Errors by Restore DB

### ISSUE THREAD

**Issue by tomep** [teksi/wastewater#94]
**Describe the bug**
I get errors by restoring the database in pdAdmin.

**To Reproduce**
1. Open pgAdmin
2. Make a new DB called "TEKSI_DSS2020_Test"
3. Rightclick on the DB and select [Restore...] from the menue
4. select the backup file via windows explorer
5. Run the restore

**Expected behavior**
no errors during the import and a success message

**Screenshots / data**
Heer the Logfile: 
[pg_error_log.zip](https://github.com/teksi/wastewater/files/13973578/pg_error_log.zip)

**Desktop (please complete the following information):**
 - QGIS Version - 3.28.11
 - Postgres - PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 - Postgis - POSTGIS="3.1.1 aaf4c79" [EXTENSION] PGSQL="130" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)"
 - Windows 10 Pro

**Comment by ponceta** [comment]
Small fix :

Create the roles on the database cluster :

https://github.com/teksi/wastewater/blob/main/datamodel/12_0_roles.sql

Should fix error

Testing discussion will be adapted.

**Comment by sjib** [comment]
See new point 0. Create the roles on the database cluster  on https://github.com/teksi/wastewater/discussions/72
